### PR TITLE
Setting up app - renamed app

### PR DESCRIPTION
**Pull request by beaesguerra**
Re-submitting a pull request to initalize the app with a different name (agritrader). 
Original pull request: https://github.com/agriculture-capstone/agritrader/pull/19

Many of the files were generated when the react native project was initialized. 

Main changes:
- Set up the mobile app using react native
- Integrated typescript
- Include readme for set up instructions
- Set up code coverage thresholds 
- See package.json, README.md, and tsconfig.json

Sample screenshot of the application in its' basic state:
image

### CODE REVIEW

**Comment by beaesguerra** [comment]
The android & ios folders are included for when we want to add native code for the app (which we probably won't need, but having them available will give us the opportunity to use them if needed).

Also, the react native project initializer generated a proper gitignore and these folders were not specified to be ignored.

**Comment by beaesguerra** [comment]
I also lowered the code coverage threshold so it is not misleading

**Comment by jeinglis** [comment]
Looks good although it took me a long time to get all my env variables set up so that it will launch (i didn't see the other tab that told you how to do it all) had to set ANDROID_HOME ---> android sdk and add adb.exe to my path. I think you should add these to the readme to make it easier for the others

**Comment by beaesguerra** [comment]
@jeinglis  updated the readme to include instructions on how to set up your device along with common issues and how to solve them

**Pull request merged**
